name: CortexPlugin
version: 1.0
api-version: 1.16
author: Junferno
main: com.junferno.cortex.CortexPlugin
description: Cortex Plugin Brain-computer Interface integration for Minecraft with Cortex API

commands:
  brainplayer:
    aliases: [bp]
    description: Manually sets brain player for Cortex reference
  open:
    description: Reconnects WebSocket to Cortex API
  close:
    description: Disconnects WebSocket from Cortex API